### ISSUE TITLE
Could not find the theme offset in the specified executable!

### ISSUE THREAD

**Issue by JethroSovr** [aevitas/unity-patch#20] opened 2020-03-12 03:56 UTC
**Description**
Thank you for your working, I want to know 2019.3.1f1 will support later or not.

**Version Information**
* What Operating System are you running the patcher on?
mac
* What Unity Version are you using?
2019.3.1f1

**Diagnostics**
What does the patcher output instead of the expected behaviour?
Could not find the theme offset in the specified executable!
**Arguments**
Please provide the exact command line arguments you are using the patcher with,
./Patcher -t=dark -mac -v=2019.3.1f1 -e=/Applications/Unity/2019.3.1f1/Unity.app/Contents/MacOS/Unity 

**Binaries**
If possible, provide a link to the Unity binary that corresponds with the version and OS you're using.

**Comment by aevitas** [comment] 2020-03-14 17:01
Treating this as a duplicate of #19 as the different minor version likely won't affect the solution much.

**Closed as completed by aevitas** 2020-03-14 17:02 UTC
Labels: bug, duplicate, os-osx, pattern-issue
