### ISSUE TITLE
command not found: Patcher on OS X

### ISSUE THREAD

**Issue by app-o-matix** [aevitas/unity-patch#25] opened 2020-04-15 01:58 UTC
**Description**
Patcher is not being recognized as a command in the terminal

**Version Information**
OS X Catalina 10.15.4
Unity 2018.4.21f1

**Diagnostics**
`sudo: osx-x64/Patcher: command not found`

**Arguments**  
Directory:

    /applications/unity/hub/editor/2018.4.21f1/ -> ls
    Documentation   PlaybackEngines   Unity Bug Reporter.app   Unity.app   modules.json   osx-x64

Command and Response:

    /applications/unity/hub/editor/2018.4.21f1/ -> sudo osx-x64/Patcher -e=Unity.app -t=dark -mac
    sudo: osx-x64/Patcher: command not found

**Comment by maximilianmaihoefner** [comment] 2020-04-15 10:00
There are multiple Issues here... The biggest one being, that even if the Patcher was being recognized as a command, it doesn't include the necessary PatchInfo for Unity 2018. It would probably make sense to get the PatchInfo for 2018.4 since it's an LTS, I will see if I can get around to decompile that release and get the necessary HexValues for it.

That being said, another Problem I can spot in the Example you gave is that on macOS you need to Point to the Unity binary and not the .app. The binary is inside the .app in `Contents/MacOS/Unity`. Meaning, the -e should get something like `Unity.app/Contents/MacOS/Unity`.

It might also help to specify the full path to the Patcher instead of a relative one. I run the Patcher using: `~/Downloads/unity-patch-v1.2/osx-x64/Patcher -mac -e /Applications/Unity/Hub/Editor/2019.3.9f1/Unity.app/Contents/MacOS/Unity -t dark` and it executes the Patcher just fine.

**Comment by app-o-matix** [comment] 2020-04-15 19:22
Thanks for the feedback. Here is what I have found:

> The biggest one being, that even if the Patcher was being recognized as a command, it doesn't include the necessary PatchInfo for Unity 2018. It would probably make sense to get the PatchInfo for 2018.4 since it's an LTS, I will see if I can get around to decompile that release and get the necessary HexValues for it.

I ended up finding the HexValues for version 2018.4.21f1 (which is the latest). The following should work:

**_(updated 04/16 for typo in hex values)_**

    new PatchInfo
    {
        Version = "2018.4.21f1",
        DarkPattern = new byte[] {0x75, 0x03, 0x41, 0x8b, 0x06, 0x4C},
        LightPattern = new byte[] {0x74, 0x03, 0x41, 0x8b, 0x06, 0x4C}
    },

> That being said, another Problem I can spot in the Example you gave is that on macOS you need to Point to the Unity binary and not the .app.

Noted. I know of the binary since it was what was needed for changing the HexValues above. Maybe in the README, the instruction could be

`sudo ./osx-x64/Patcher -e=/path/to/UnityBinary -t=dark -mac`, path e.g. `/Applications/Unity/Hub/Editor/2018.4.21f1/Unity.app/Contents/MacOS/Unity`

for those like me, who might need a little extra handholding. :grinning:  

> It might also help to specify the full path to the Patcher instead of a relative one.

It's actually not a relative path. I temporarily moved Patcher into the Unity folder to simplify my paths in the command line. :grimacing: Having both moved Patcher into the folder with the binary, as well as using the command exactly as you indicate above, I'm still getting the `sudo: osx-x64/Patcher: command not found` response. Still not sure if Patcher isn't working properly for Mac or I'm simply still doing something wrong.

Thanks!

**Comment by maximilianmaihoefner** [comment] 2020-04-16 09:22
Interesting, you found a different HexValue than what I found yesterday. Did you apply that Hex manually and does it work?

It sounds like a good idea to me to document that you need to point to the Binary inside the `.app`. I also talked to @aevitas and we had the idea to simplify how the Patcher is run, I created an Issue outlining the changes in #28, you can also contribute ideas and suggestions there.

Sorry I missed that you moved the Patcher in the Unity Directory. I am also and Mac and for me it runs fine. Which shell are you using? I use prezto (a zsh flavor), but I heard that Catalina now comes with zsh as default instead of bash. Could you also try to start the Unity Binary from the Shell, `/Applications/Unity/Hub/Editor/2018.4.21f1/Unity.app/Contents/MacOS/Unity` to see if that works or if it also says that Unity is not a command.

**Comment by denostr** [comment] 2020-04-16 12:30
Same problem, for 2019.3.9f1

Running command:
```
sudo /path/to/Patcher/osx-64/Patcher -mac -e /Applications/Unity/Hub/Editor/2019.3.9f1/Unity.app/Contents/MacOS/Unity -t dark
```

And got `sudo: /path/to/Patcher/osx-64/Patcher: command not found`

**Comment by aevitas** [comment] 2020-04-16 12:35
Did you make sure the path to the patcher is correct for your local system?
/path/to/Patcher is a placeholder and wont work directly.

**Comment by denostr** [comment] 2020-04-16 13:26
Yes, checked it twice

**Comment by maximilianmaihoefner** [comment] 2020-04-16 13:40
I've checked again, I can not reproduce the Issue on neither of my Macs. I found another Issue with the new notarization introduced in macOS Catalina, but that should not be related.

When I download the latest Patcher from the releases and run:
`./Patcher`
it outputs:
`zsh: permission denied: ./Patcher`
Then I make the Patcher executable by running:
`chmod +x Patcher`
and run `./Patcher` again. Then the notarization Issue kicks in wanting me to explicitly allow all dlls to be executed which are referenced. After allowing all the dlls the Patcher runs fine.

Can either of you try to describe the steps you took and the Environment you are running?

**Comment by denostr** [comment] 2020-04-16 15:23
Thanks `chmod +x Patcher` solve the problem for my case too.
After that i grant access to all dll files. 
And after that got `Can not patch the specified file - it is marked as read only!`. 
I changed Unity file permission. It's work, but now Patcher response:
`Error: Could not find the theme offset in the specified executable`
Added `-version` param to command line, but it does not help

**Comment by maximilianmaihoefner** [comment] 2020-04-16 16:40
We should probably mention the `chmod` in the Readme then, although the sudo error could be a bit more descriptive too.

Which version of Unity are you trying to patch? Unity 2019.3 requires the new version of the patcher released yesterday (1.3).

**Comment by app-o-matix** [comment] 2020-04-16 21:01
@maximilianmaihoefner 

> Interesting, you found a different HexValue than what I found yesterday. Did you apply that Hex manually and does it work?

Sorry, I mistyped it. I've corrected it above (`0x18` -> `0x41`). And it is working for me, so I'm guessing it is now the same as yours. Once changed, you still don't have the option to select between light and dark theme in the Unity preferences (as I've seen in some hex value change examples) -- that is still grayed out. It simply launches in dark theme.

> Which shell are you using?

I'm using zsh/OhMyZsh, installed via Homebrew prior to my upgrade to Catalina, iirc.

> Could you also try to start the Unity Binary from the Shell

So, in the directory of the binary (/MacOS) if I just type `Unity` at the command prompt, it does not recognize `Unity` as a command. If I enter it as `./Unity`, then it launches Unity. I'm guessing the same would be true of Patcher, as you suggest above. I haven't tried it again. This seems to tie into your discussion with @denostr above and this old SO question and responses:

[Running an executable in Mac Terminal](https://stackoverflow.com/questions/15080835/running-an-executable-in-mac-terminal)

> We should probably mention the chmod in the Readme

In the guide I used, once you've changed the hex values, you `chmod 777` the new Unity binary. So, whatever is appropriate for the Patcher (e.g. `+x`), then yeah.

**Comment by denostr** [comment] 2020-04-17 06:18
@maximilianmaihoefner 

> Which version of Unity are you trying to patch? Unity 2019.3 requires the new version of the patcher released yesterday (1.3).

Unity version `2019.3.9f1` (latest)
Patcher version `1.3`

**Comment by maximilianmaihoefner** [comment] 2020-04-17 08:00
Can you try running the Patcher with `--version=2019.3.0f6` (the Hex Values stayed the same for 2019.3.9f1). If that doesn't work could you post the complete output the patcher gives you.

**Comment by denostr** [comment] 2020-04-17 09:23
> Can you try running the Patcher with --version=2019.3.0f6 (the Hex Values stayed the same for 2019.3.9f1)

Yes, it works! Thanks a lot

**Closed as completed** 2020-04-17 09:29 UTC
